# -----------------------------
# 1. Build
# -----------------------------
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

# csproj'u kopyala ve restore yap
COPY ./ApiGateway/ApiGateway.csproj ./
RUN dotnet restore

# Tüm proje dosyalarını kopyala
COPY ./ApiGateway/. ./

# Publish
RUN dotnet publish -c Release -o /app/publish

# -----------------------------
# 2. Runtime
# -----------------------------
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 5179
ENTRYPOINT ["dotnet", "ApiGateway.dll"]
