# -----------------------------
# 1. Build
# -----------------------------
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

ENV DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1

# Projeleri kopyala
COPY ./LogService.API/LogService.API.csproj ./LogService.API/
COPY ./LogService.Application/*.csproj ./LogService.Application/
COPY ./LogService.Core/*.csproj ./LogService.Core/
COPY ./LogService.Infrastructure/*.csproj ./LogService.Infrastructure/

WORKDIR /app/LogService.API
RUN dotnet restore

# Kaynakları kopyala (obj/bin dahil değil)
COPY ./LogService.API/. ./LogService.API/
COPY ./LogService.Application/. ./LogService.Application/
COPY ./LogService.Core/. ./LogService.Core/
COPY ./LogService.Infrastructure/. ./LogService.Infrastructure/

# Publish
RUN dotnet publish -c Release -o /app/publish /p:GenerateAssemblyInfo=false /p:UseSharedCompilation=false /p:UseAppHost=false

# -----------------------------
# 2. Runtime
# -----------------------------
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
COPY ./LogService.API/appsettings.json .
EXPOSE 5216
ENTRYPOINT ["dotnet", "LogService.API.dll"]
